name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    name: build and release docker image
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: crashkursyildirim.azurecr.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: crashkursyildirim.azurecr.io/ttd-frontend:${{ github.run_number }}

  deploy:
    name: deploy new image
    needs: [docker]
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: 20.160.229.65
        username: deploy
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
            docker stop ttd_frontend || true 
            docker rm -f ttd_frontend || true
            docker run -d --name ttd_frontend -p8080:80 crashkursyildirim.azurecr.io/ttd-frontend:${{ github.run_number }}
